import jsPDF from "jspdf";
import NotoSans from "../fonts/NotoSans.ttf";
import { loadFontAsBase64 } from "./loadFont";

export async function generatePDF(result: any) {
  const doc = new jsPDF();

  const fontBase64 =
  await loadFontAsBase64(NotoSans);

doc.addFileToVFS(
  "NotoSans.ttf",
  fontBase64
);

doc.addFont(
  "NotoSans.ttf",
  "NotoSans",
  "normal"
);

doc.setFont("NotoSans");
  

  const pageHeight = doc.internal.pageSize.height;

  function checkPageBreak(
    currentY: number,
    extraSpace: number
  ) {
    if (currentY + extraSpace > pageHeight - 20) {
      doc.addPage();
      return 20;
    }

    return currentY;
  }

  // ========================
  // HEADER
  // ========================

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(22);

  doc.text(
    "ScamShield AI Threat Report",
    20,
    20
  );

  doc.setDrawColor(124, 58, 237);
  doc.setLineWidth(1);

  doc.line(
    20,
    28,
    190,
    28
  );

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(10);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    35
  );

  // ========================
  // THREAT SUMMARY
  // ========================

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(13);

  doc.text(
    "THREAT SUMMARY",
    20,
    45
  );
  doc.setFont("NotoSans", "normal");
  doc.setFontSize(11);

  doc.text(
    `Risk Score: ${result.riskScore}%`,
    20,
    55
  );

  doc.text(
    `Risk Level: ${result.riskLevel}`,
    20,
    65
  );

  doc.text(
    `Category: ${result.category}`,
    20,
    75
  );

  doc.text(
    `Confidence: ${result.confidence}%`,
    20,
    85
  );

  // Start BELOW summary
  let y = 100;

  // ========================
  // THREAT INDICATORS
  // ========================

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(13);

  doc.text(
    "THREAT INDICATORS",
    20,
    y
  );
  y += 6;

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(11);

  result.threatIndicators.forEach(
    (indicator: string) => {
      y = checkPageBreak(y, 20);

      const wrapped =
        doc.splitTextToSize(
          `• ${indicator}`,
          160
        );

      doc.text(
        wrapped,
        25,
        y
      );

      y += wrapped.length * 5 + 1;
    }
  );

  // ========================
  // SIMPLE EXPLANATION
  // ========================

  y += 8;

  y = checkPageBreak(y, 40);

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(13);

  doc.text(
    "SIMPLE EXPLANATION",
    20,
    y
  );


  y += 6;

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(11);

  const simpleText =
    doc.splitTextToSize(
      result.simpleExplanation,
      160
    );

  doc.text(
    simpleText,
    20,
    y
  );

  y += simpleText.length * 5 + 8;

  // ========================
  // DETAILED ANALYSIS
  // ========================

  y = checkPageBreak(y, 50);

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(13);

  doc.text(
    "DETAILED ANALYSIS",
    20,
    y
  );

  y += 8;

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(11);

  const detailedText =
    doc.splitTextToSize(
      result.explanation,
      160
    );

  doc.text(
    detailedText,
    20,
    y
  );

  y += detailedText.length * 5 + 8;

  // ========================
  // RECOMMENDATIONS
  // ========================

  y = checkPageBreak(y, 50);

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(13);

  doc.text(
    "RECOMMENDATIONS",
    20,
    y
  );
  y += 6;

  doc.setFont("NotoSans", "normal");
  doc.setFontSize(11);

  result.recommendations.forEach(
    (rec: string) => {
      y = checkPageBreak(y, 20);

      const wrapped =
        doc.splitTextToSize(
          `• ${rec}`,
          160
        );

      doc.text(
        wrapped,
        25,
        y
      );

      y += wrapped.length * 5 + 1;
    }
  );

  // ========================
  // FOOTER
  // ========================

  const totalPages =
    doc.getNumberOfPages();

  for (
    let i = 1;
    i <= totalPages;
    i++
  ) {
    doc.setPage(i);

    doc.setFontSize(9);

    doc.setTextColor(
      120,
      120,
      120
    );

    doc.text(
      "Generated by ScamShield AI",
      20,
      287
    );

    doc.text(
      `Page ${i}`,
      180,
      287
    );
  }

  doc.save(
    "ScamShield_Report.pdf"
  );
}